### ISSUE TITLE
オプション：テキスト・URLのカスタマイズ

### ISSUE THREAD

**Issue by inductor** [qrac/ie-buster#13]
- 日本語のみ
- ブラウザがChromeのみ
- セキュリティリスクってほんとにいいのかな？

とかが気になったので、もしよろしければ動的に文言が書き換えられるようになったらいいなと思ってます。

**Comment by qrac** [comment]
ありがとうございます！
確かに、その方が良いですね。オプション機能の実装を試してみます！

**Comment by qrac** [comment]
![image](https://user-images.githubusercontent.com/9658016/46136231-18a7fe80-c282-11e8-906d-ae0f62570bb8.png)

ライブラリ読み込み後に、代替テキストをオプションで渡して差し替えるテストを行いました。

**Comment by qrac** [comment]
![image](https://user-images.githubusercontent.com/9658016/46130398-32dae000-c274-11e8-8311-c8db01bf8774.png)

IE8 テスト。

**Comment by qrac** [comment]
@inductor v1.1.0にて反映させていただきました。ご提案ありがとうございます！
