### ISSUE TITLE
モダンブラウザではスクリプトを読み込まないようにしたい

### ISSUE THREAD

**Issue by iMasanari** [qrac/ie-buster#28]
v2を開発中とのことで、表題の件をご提案いたします。
`<script nomodule>` を利用した場合、モダンブラウザではそのスクリプトを読み込みません。これを利用して、IEを含むレガシーなブラウザでのみ IE Buster を読み込ませることで、実質的に軽量化となります。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/script#attr-nomodule
https://caniuse.com/mdn-html_elements_script_nomodule

下記の通り懸念点もありますが、ご検討いただけますでしょうか。

## 使用方法

```html
<script nomodule src="ie-buster.js"></script>
```

`import`などで組み込むと効果がないので、CDNを利用するのがベストだと思います。

## 懸念点

モダンブラウザの場合、スクリプトが読み込まれず `ieBuster` 関数は存在しません。なので、Option設定時の方法を変更する必要があります。

```html
<!-- 案1: 存在チェック -->
<script nomodule src="ie-buster.js"></script>
<script>
  typeof ieBuster === 'function' && ieBuster({
    mainText: "...",
    linkText: "...",
    linkUrl: "..."
  })
</script>
```

```html
<!-- 案2: html内で記述するよう変更する -->
<script
  nomodule
  src="ie-buster.js"
  id="ie-buster-script"
  data-main-text="..."
  data-link-text="..."
  data-link-url="..."
></script>
```

案2の方は、下記に仮実装がありますので、ご参考になれば幸いです。
https://github.com/iMasanari/ie-buster/blob/use-nomodule/src/app/ie-buster.js

**Comment by qrac** [comment]
なるほど、そのような読み込み方があるんですね！
案1であれば、CDNの使い方を変えるだけで済みそうなので、案1をテクニックとしてドキュメントに追記するのが良いかと思いました。

**Comment by iMasanari** [comment]
確かにテクニックとして紹介するのがソースの変更もなく、良さそうですね。

また、案3を用意いたしました。案1よりもシンプルになっています。

```html
<!-- 案3: スクリプト読み込み、オプション指定の両方に `nomodule` -->
<script nomodule src="ie-buster.js"></script>
<script nomodule>
  ieBuster({
    mainText: "...",
    linkText: "...",
    linkUrl: "..."
  })
</script>
```

**Comment by qrac** [comment]
お、それでもいけるんですね。ありがとうございます！

**Comment by qrac** [comment]
案3が利用方法も自然で動作も問題ありませんでしたので、デフォルトのCDN記述方法にさせていただきました！ご提案ありがとうございました👏
